Implement test failure check in unit tests workflow
Add a step to check for test failures in the CI workflow.

diff --git a/.github/workflows/unit-tests.yaml b/.github/workflows/unit-tests.yaml
--- a/.github/workflows/unit-tests.yaml
+++ b/.github/workflows/unit-tests.yaml
@@ -49,3 +49,11 @@ jobs:
         with:
           name: jacoco-coverage-report
           path: "**/target/site/jacoco/"
+
+      - name: Check for Test Failures
+        if: always()
+        run: |
+          if grep -q "<failure" target/surefire-reports/*.xml; then
+          echo "Tests failed, failing the build."
+          exit 1
+          fi
